# Generated by Django 5.2.7 on 2025-10-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(db_index=True, help_text='Title of the article edited.', max_length=500)),
                ('user_name', models.CharField(db_index=True, help_text='User who made the edit.', max_length=200)),
                ('edit_timestamp', models.DateTimeField(db_index=True, help_text='The time the edit occurred.')),
                ('byte_change', models.IntegerField(default=0, help_text='Change in bytes (+ or -) of the article size.')),
                ('is_minor', models.BooleanField(default=False, help_text='True if the edit was marked as minor.')),
                ('edit_url', models.URLField(help_text='URL linking to the edit/diff.', max_length=1000)),
            ],
            options={
                'verbose_name': 'Wikipedia Edit',
                'verbose_name_plural': 'Wikipedia Edits',
                'ordering': ['-edit_timestamp'],
            },
        ),
    ]
